# Generated by Django 5.2.6 on 2025-09-24 07:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artisan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=128)),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('slug', models.SlugField(blank=True, max_length=400, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Base retail price of the product.', max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('images', models.JSONField(blank=True, default=list)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('story_markdown', models.TextField(blank=True)),
                ('origin_region', models.CharField(blank=True, max_length=128)),
                ('royalty_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Royalty percentage paid to the creator on resale.', max_digits=5)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('artisan', models.ForeignKey(blank=True, help_text='Optional artisan (non-designer) linked to the product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.artisan')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
                ('designer', models.ForeignKey(blank=True, help_text='The designer associated with this product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='designers.designerprofile')),
            ],
        ),
    ]
