# Generated by Django 5.2.6 on 2025-09-21 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_set_system_role'),
        ('users', '0004_set_system_role'),
    ]

    operations = [
    ]
